ROOT_DIR         ?= ../..
PIPIT_DIR        ?= ../../pipit
COMPONENT        ?= ttcan
FSTAR_INC_DIRS   ?= base core rts/fstar abstract extract plugin/fst plugin/_build/default source
FSTAR_SRC_DIRS   ?= .
FSTAR_ALREADY_CACHED ?=

FSTAR_EXTRA_OPT += --warn_error -249

include $(ROOT_DIR)/make/include/base.mk