ROOT_DIR 			?= ..
PIPIT_DIR 				?= ../pipit
COMPONENT   		?= example
FSTAR_INC_DIRS 	?= base core rts/fstar abstract extract source
FSTAR_SRC_DIRS 	?= .
FSTAR_ALREADY_CACHED ?=


include $(ROOT_DIR)/make/include/base.mk

# TODO: extraction is disabled

