ROOT_DIR 				?= ../..
PIPIT_DIR 			?= ..
COMPONENT   		?= plugin-test
FSTAR_INC_DIRS 	?= base core rts/fstar abstract extract plugin/fst plugin/_build/default source
FSTAR_SRC_DIRS 	?= .
FSTAR_ALREADY_CACHED ?=


include $(ROOT_DIR)/make/include/base.mk

